plugins:
    markdownlint:
        enabled: true
        issue_override:
            severity: minor
    editorconfig:
        enabled: true
        issue_override:
            severity: minor
    checkstyle:
        enabled: true
        config: 'java/checkstyle.xml'

exclude_patterns:
    - "/.idea/"
